name:                ResourceAllocation
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- warp
- wai
- http-types

library:
  source-dirs: src

executables:
  HelloWorld-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HelloWorld

tests:
  HelloWorld-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HelloWorld
